### ISSUE TITLE
[XF] IMobileRTCMeetingServiceDelegate cannot be found in ios Xamarin Forms

### ISSUE THREAD

**Issue by sekhonitconsultants** [VisualService/dotnet-zoom-meeting-SDK#18] opened 2023-01-26 16:23 UTC
Hi Guys, IMobileRTCMeetingServiceDelegate cannot be found in ios Xamarin forms, any help to resolve this issue will be much appreciated.
Thanks a million

**Comment by sekhonitconsultants** [comment] 2023-01-26 17:55
I downloaded the source code and build fine, than I removed the nuget package from xamarin forms ios project and used the compiled .dll for reference, all worked as expected. Not sure why nuget pacakge does not work.
Anyway great nuget package guys great help.

**Comment by mdima** [comment] 2023-01-27 13:45
Hi @sekhonitconsultants , thank you for using the project and appreciating it. 
About the issue in the Nuget package, really don't know... probably there is some dependency not working, anyway I am happy you found the project useful. 
If you find out the reason why the Nuget package fails, please add the contribution to the project. 
Thanks, Michele

**Comment by sekhonitconsultants** [comment] 2023-04-26 15:27
Hi @mdima , You had motivated me to get it fixed so I had some time to get it fixed, please review my change. All it needed was to change the Res/Icon.png build action to Content. I have also update one of the existing package.

Thanks,
Bahadur

**Comment by AdamDiament** [comment] 2023-05-07 10:02
Thankyou @sekhonitconsultants ! Could you raise a PR so I can review your changes please?

**Comment by sekhonitconsultants** [comment] 2023-05-09 15:57
That is done now @AdamDiament , please let me know if it is working okey.

Thanks 
Bahadur

**Comment by AdamDiament** [comment] 2023-09-06 05:44
Closing as it is a duplicate of #10, which itself may be fixed. Note for @timjamwoo to check if we can produce a nuget output for iOS

**Closed by AdamDiament** 2023-09-06 05:44 UTC
